<?php

namespace ContainerH9bMz7h;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_Product_RepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'app.product.repository' shared autowired service.
     *
     * @return \App\Repository\ProductRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/lib/Doctrine/Persistence/ObjectRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/collections/lib/Doctrine/Common/Collections/Selectable.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/lib/Doctrine/ORM/EntityRepository.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/doctrine-bundle/Repository/ServiceEntityRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Repository/ProductRepository.php';
        include_once \dirname(__DIR__, 4).'/src/Service/ImageUploader.php';

        return $container->privates['app.product.repository'] = new \App\Repository\ProductRepository(($container->services['doctrine'] ?? $container->getDoctrineService()), ($container->privates['App\\Service\\ImageUploader'] ?? ($container->privates['App\\Service\\ImageUploader'] = new \App\Service\ImageUploader())));
    }
}
