<?php

namespace ContainerYz4d5I4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApp_Cart_ControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'app.cart.controller' shared autowired service.
     *
     * @return \App\Controller\CartController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ApiController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/CartController.php';

        $container->services['app.cart.controller'] = $instance = new \App\Controller\CartController(($container->privates['app.cart.repository'] ?? $container->load('getApp_Cart_RepositoryService')), ($container->privates['app.product.repository'] ?? $container->load('getApp_Product_RepositoryService')), 'Psr\\Log\\LoggerInterface');

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->load('get_ServiceLocator_5nX7ca3Service'))->withContext('app.cart.controller', $container));

        return $instance;
    }
}
