<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYz4d5I4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYz4d5I4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYz4d5I4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYz4d5I4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYz4d5I4\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yz4d5I4',
    'container.build_id' => '0542a1c5',
    'container.build_time' => 1614554735,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYz4d5I4');
