<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8uxdFzx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8uxdFzx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8uxdFzx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8uxdFzx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8uxdFzx\App_KernelDevDebugContainer([
    'container.build_hash' => '8uxdFzx',
    'container.build_id' => 'df30e69b',
    'container.build_time' => 1614355703,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8uxdFzx');
